import turtle as t
def triangle(lenght, color):
    t.color(color)
    t.begin_fill()
    for i in range(3):
        t.left(120)
        t.forward(lenght)
    t.end_fill()

def change_position(x_position,y_position):
    t.penup()
    t.goto(x=x_position,y=y_position)
    t.pendown()

def tree():
    t.left(90)
    t.color("brown")
    t.begin_fill()
    t.forward(50)
    t.end_fill()
    t.right(90)
    t.color("green")
    t.begin_fill()
    t.circle(25)
    t.end_fill()

def bird():
    for i in range(2):
        t.right(125)
        t.forward(25)
    t.right(110)

def sun():
    t.color('yellow')
    t.begin_fill()
    t.circle(50)
    t.end_fill()
    t.penup()
    t.goto(-505,160)
    t.pendown()
    t.left(120)
    t.forward(25)
    t.penup()
    t.goto(-415, 145)
    t.pendown()
    t.forward(25)
    t.penup()
    t.goto(-455, 95)
    t.pendown()
    t.forward(25)
    t.penup()
    t.goto(-505, 50)
    t.pendown()
    t.forward(25)
    t.penup()
    t.goto(-415, 25)
    t.pendown()
    t.forward(25)
    t.penup()
    t.goto(-455, -35)
    t.pendown()
    t.forward(25)
    t.penup()
    t.goto(-330, -15)
    t.pendown()
    t.forward(25)
    t.penup()
    t.goto(355, 50)
    t.pendown()
    t.left(240)

def name():
    t.pencolor("black")
    t.forward(45)
    t.left(140)
    t.forward(45)
    t.right(140)
    t.forward(45)
    t.penup()
    t.goto(365,85 )
    t.pendown()
    t.right(120)
    t.forward(45)
    t.right(120)
    t.forward(45)
    t.right(120)
    t.left(90)
    t.penup()
    t.goto(395, 45)
    t.pendown()
    t.color("black")
    t.forward(35)
    t.penup()
    t.goto(405, 95)
    t.pendown()
    t.begin_fill()
    t.circle(10)
    t.end_fill()
    t.penup()
    t.goto(465, 60)
    t.pendown()
    t.circle(20)
    t.right(90)
    t.penup()
    t.goto(460, 50)
    t.pendown()
    t.forward(15)
    t.right(90)
    t.penup()
    t.goto(505, 85)
    t.pendown()
    t.forward(45)
    t.left(90)
    t.forward(20)
    t.penup()
    t.goto(490, 60)
    t.pendown()
    t.forward(30)
    t.penup()
    t.goto(150, 150)
    t.pendown()


def bottom ():
    t.color("Tan")
    t.begin_fill()
    for i in range(2):
        t.forward(1450)
        t.left(90)
        t.forward(250)
        t.left(90)
    t.end_fill()

def up():
    t.pendown()
    t.color("light blue")
    t.begin_fill()
    for i in range(2):
        t.forward(1450)
        t.left(90)
        t.forward(515)
        t.left(90)
    t.end_fill()

def red():
    t.color("red2")
    t.begin_fill()
    for i in range(2):
        t.forward(1450)
        t.left(90)
        t.forward(50)
        t.left(90)
    t.end_fill()

def blue():
    t.color("blue2")
    t.begin_fill()
    for i in range(2):
        t.forward(650)
        t.left(90)
        t.forward(428)
        t.left(90)
    t.end_fill()

def star():
    t.pencolor("black")
    for i in range(5):
        t.forward(30)
        t.right(144)