# import turtle as t
# t.shape("turtle")
# t.speed(50)
# t.color("yellow")
# t.begin_fill()
# t.circle(50)
# t.end_fill()
# t.penup()
# t.goto(50,50)
# t.left(180)
# t.pendown()
# t.forward(400)
# t.left(90)
# t.color("yellow")
# t.begin_fill()
# t.circle(50)
# t.end_fill()
# t.penup()
# t.goto(-300,50)
# t.left(180)
# t.pendown()
# t.forward(50)
# t.color("black")
# t.begin_fill()
# t.forward(155)
# t.right(90)
# t.forward(195)
# t.right(55)
# t.forward(190)
# t.end_fill()
# t.penup()
# t.goto(-250,225)
# t.right(35)
# t.pendown()
# t.color("light blue")
# t.begin_fill()
# for i in range(4):
#     t.forward(45)
#     t.left(90)
# t.end_fill()
# t.penup()
# t.goto(-125,225)
# t.pendown()
# t.color("light green")
# t.begin_fill()
# for i in range(4):
#     t.forward(45)
#     t.right(90)
# t.end_fill()
# t.penup()
# t.goto(-95,145)
# t.pendown()
# t.color("orange")
# t.right(65)
# t.forward(50)
# t.right(25)
# t.forward(105)
# t.right(35)
# t.forward(25)
# t.done()

# import turtle as t
# t.shape("turtle")
# t.forward(170)
# t.left(115)
# t.forward(200)
# t.left(130)
# t.forward(200)
# t.done()

# import turtle as t
# t.shape("turtle")
# t.speed(10)
# for i in range(8):
#     t.circle(50)
#     t.left(45)
# t.done()

# import turtle as t
# t.penup()
# t.goto(150,-150)
# t.pendown()
# t.forward(100)
# t.done()

# import turtle as t
# t.color("green", "red")
# t.begin_fill()
# for i in range(4):
#     t.forward(100)
#     t.left(90)
# t.end_fill()
# t.done()

# import turtle as t
# t.shape("turtle")
# t.color("red", "orange")
# t.begin_fill()
# t.forward(225)
# t.left(125)
# t.forward(200)
# t.left(110)
# t.forward(200)
# t.color("light blue")
# t.end_fill()
# t.done()